"use client";
import { Copy, ExternalLink, Save } from "lucide-react";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { WorkspaceShell } from "./workspace-shell";
import { useWorkspace } from "./workspace-provider";
import { SpecialServicesEditor, type SpecialService } from "./special-services-editor";
const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000/v1";
const days = ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"];
const services = [{ key: "lunch", label: "Almuerzo", startTime: "12:00", endTime: "15:00" }, { key: "dinner", label: "Cena", startTime: "20:00", endTime: "23:00" }] as const;
type publicThemeKey = "classic" | "campo" | "bistro";
const publicThemes: Array<{ key: publicThemeKey; label: string; description: string; accent: string; swatch: [string, string, string] }> = [
  { key: "classic", label: "Actual", description: "Tarjeta moderna con tu color de marca.", accent: "#FF5A00", swatch: ["#FFFFFF", "#F7F7F5", "#FF5A00"] },
  { key: "campo", label: "Campo", description: "Papel crema, tipografía serif y cinta borgoña.", accent: "#7B2D26", swatch: ["#F3EEE6", "#FBF8F2", "#7B2D26"] },
  { key: "bistro", label: "Bistró", description: "Editorial oscuro con detalles dorados.", accent: "#C9A227", swatch: ["#141210", "#1E1B18", "#C9A227"] }
];
const accentPresets = ["#FF5A00", "#7B2D26", "#C9A227", "#1F6F5C", "#1D4ED8", "#111827"];
type Window = { branchId: string; weekday: number; service: "lunch" | "dinner"; isEnabled: boolean; startTime: string; endTime: string; intervalMin: number };
type ExceptionWindow = Omit<Window, "branchId" | "weekday" | "isEnabled">; type Exception = { branchId: string; serviceDate: string; type: string; windows: ExceptionWindow[] };
type Settings = { isEnabled: boolean; coverImageUrl?: string | null; accentColor: string; publicTheme: publicThemeKey; minAdvanceMinutes: number; maxAdvanceDays: number; minPartySize: number; maxPartySize: number; largePartyThreshold?: number | null; agencyPartyThreshold?: number | null };
type Config = { restaurant: { slug: string; branches: { id: string; name: string; onlineBookingDurationMinutes: number }[] }; settings: Settings; bookingWindows: Window[]; exceptions: Exception[] };
type Draft = { branchId: string; serviceDate: string; rows: SpecialService[]; savedRows: SpecialService[]; allRows: SpecialService[]; loading: boolean };
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block space-y-2 text-sm font-semibold text-brand-ink"><span>{label}</span>{children}</label>; }

export function OnlineBookingsPage({ mode = "public" }: { mode?: "rules" | "public" }) {
 const { token, currentUser } = useWorkspace(); const [config, setConfig] = useState<Config | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [saved, setSaved] = useState(false);
 const [special, setSpecial] = useState<Draft>({ branchId: "", serviceDate: "", rows: [], savedRows: [], allRows: [], loading: false }); const [pending, setPending] = useState<Pick<Draft, "branchId" | "serviceDate"> | null>(null);
 const specialDirty = JSON.stringify(special.rows) !== JSON.stringify(special.savedRows);
 useEffect(() => { if (!token) return; fetch(`${API_URL}/restaurant/online-booking`, { headers: { Authorization: `Bearer ${token}` } }).then(async r => { if (!r.ok) throw new Error("No se pudo cargar la configuración"); return r.json() as Promise<Config>; }).then(data => { const known = new Set((data.bookingWindows || []).map(x => `${x.branchId}:${x.weekday}:${x.service}`)); const defaults = data.restaurant.branches.flatMap(branch => days.flatMap((_, weekday) => services.map(service => ({ branchId: branch.id, weekday, service: service.key, isEnabled: false, startTime: service.startTime, endTime: service.endTime, intervalMin: 15 })).filter(x => !known.has(`${x.branchId}:${x.weekday}:${x.service}`)))); setConfig({ ...data, bookingWindows: [...(data.bookingWindows || []), ...defaults], exceptions: data.exceptions || [] }); setSpecial(x => x.branchId ? x : { ...x, branchId: data.restaurant.branches[0]?.id || "" }); }).catch(e => setError(e instanceof Error ? e.message : "No se pudo cargar")); }, [token]);
 useEffect(() => { if (!special.branchId) return; let active = true; setSpecial(x => ({ ...x, loading: true })); const query = new URLSearchParams({ branchId: special.branchId }); if (special.serviceDate) query.set("serviceDate", special.serviceDate); fetch(`${API_URL}/restaurant/online-booking/special-services?${query}`, { headers: { Authorization: `Bearer ${token}` } }).then(async r => { if (!r.ok) throw new Error("No se pudieron cargar los servicios especiales."); return r.json() as Promise<SpecialService[]>; }).then(rows => { if (active) setSpecial(x => ({ ...x, rows: x.serviceDate ? rows : [], savedRows: x.serviceDate ? rows : [], allRows: rows, loading: false })); }).catch(e => { if (active) { setError(e instanceof Error ? e.message : "No se pudieron cargar los servicios especiales."); setSpecial(x => ({ ...x, loading: false })); } }); return () => { active = false; }; }, [special.branchId, special.serviceDate, token]);
 const update = (key: keyof Settings, value: string | boolean | number | null) => setConfig(c => c ? { ...c, settings: { ...c.settings, [key]: value } } : c);
 const updateWindow = (branchId: string, weekday: number, service: Window["service"], key: keyof Window, value: string | boolean | number) => setConfig(c => c ? { ...c, bookingWindows: c.bookingWindows.map(x => x.branchId === branchId && x.weekday === weekday && x.service === service ? { ...x, [key]: value } : x) } : c);
 const addException = (branchId: string) => setConfig(c => c ? { ...c, exceptions: [...c.exceptions, { branchId, serviceDate: "", type: "closed", windows: [] }] } : c);
 const updateException = (index: number, patch: Partial<Exception>) => setConfig(c => c ? { ...c, exceptions: c.exceptions.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) } : c);
 const removeException = (index: number) => setConfig(c => c ? { ...c, exceptions: c.exceptions.filter((_, itemIndex) => itemIndex !== index) } : c);
 const saveSpecial = async () => { if (!specialDirty) return; if (!special.serviceDate || special.rows.length < 2) throw new Error("Configurá al menos dos servicios para esta fecha."); const r = await fetch(`${API_URL}/restaurant/online-booking/special-services`, { method: "PUT", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ branchId: special.branchId, serviceDate: special.serviceDate, services: special.rows }) }); if (!r.ok) throw new Error((await r.json().catch(() => null))?.message || "No se pudieron guardar los servicios especiales."); const rows = await r.json() as SpecialService[]; setSpecial(x => ({ ...x, rows, savedRows: rows })); };
 const save = async () => { if (!config) return; setSaving(true); setSaved(false); setError(""); try { await saveSpecial(); const r = await fetch(`${API_URL}/restaurant/online-booking`, { method: "PUT", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ ...config.settings, branchDurations: config.restaurant.branches.map(x => ({ branchId: x.id, durationMinutes: x.onlineBookingDurationMinutes })), bookingWindows: config.bookingWindows, exceptions: config.exceptions }) }); if (!r.ok) throw new Error("No se pudo guardar"); setConfig(await r.json()); setSaved(true); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo guardar"); } finally { setSaving(false); } };
 const select = (next: Pick<Draft, "branchId" | "serviceDate">) => { if (next.branchId === special.branchId && next.serviceDate === special.serviceDate) return; if (specialDirty) setPending(next); else setSpecial(x => ({ ...x, ...next })); };
 const continueAfterSave = async () => { if (!pending) return; setSaving(true); try { await saveSpecial(); setSpecial(x => ({ ...x, ...pending })); setPending(null); } catch (e) { setError(e instanceof Error ? e.message : "No se pudieron guardar los servicios especiales."); } finally { setSaving(false); } };
 const title = mode === "rules" ? "Reservas" : "Reservas online"; const publicUrl = useMemo(() => config ? `${window.location.origin}/reservar/${config.restaurant.slug}` : "", [config]);
 if (currentUser?.role !== "restaurant_owner") return <WorkspaceShell title={title} description="Configuración"><p>No tenés permiso para editar esta configuración.</p></WorkspaceShell>; if (!config) return <WorkspaceShell title={title} description="Configuración"><p>{error || "Cargando configuración..."}</p></WorkspaceShell>;
 return <WorkspaceShell title={title} description="Horarios y reglas compartidos por panel, web y WhatsApp."><div className="space-y-6">{mode === "public" ? <Public config={config} url={publicUrl} update={update} /> : <><Rules settings={config.settings} update={update}/><Schedules branches={config.restaurant.branches} windows={config.bookingWindows} update={updateWindow}/><SpecialServicesEditor branches={config.restaurant.branches} branchId={special.branchId} serviceDate={special.serviceDate} rows={special.rows} dirty={specialDirty} loading={special.loading} onBranchChange={branchId => select({ branchId, serviceDate: special.serviceDate })} onDateChange={serviceDate => select({ branchId: special.branchId, serviceDate })} onRowsChange={rows => setSpecial(x => ({ ...x, rows }))}/><Exceptions branches={config.restaurant.branches} values={config.exceptions} add={addException} update={updateException} remove={removeException}/></>}<div className="flex items-center justify-end gap-4"><p className="text-sm font-semibold text-emerald-700">{saved ? "Cambios guardados" : ""}</p><button disabled={saving || special.loading} onClick={() => void save()} className="inline-flex items-center gap-2 rounded-full bg-brand-orange px-6 py-3 font-bold text-white disabled:opacity-60"><Save className="h-4 w-4" />{saving ? "Guardando..." : "Guardar cambios"}</button></div>{error ? <p className="text-sm text-red-600">{error}</p> : null}</div>{pending ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div role="dialog" aria-modal="true" className="w-full max-w-md rounded-3xl bg-white p-6 shadow-xl"><h2 className="text-lg font-extrabold">Hay cambios sin guardar</h2><p className="mt-2 text-sm text-neutral-600">Guardalos antes de cambiar de sede o fecha para no perderlos.</p><div className="mt-5 flex justify-end gap-2"><button onClick={() => setPending(null)} className="rounded-full border px-4 py-2 font-bold">Cancelar</button><button onClick={() => { setSpecial(x => ({ ...x, ...pending })); setPending(null); }} className="rounded-full border border-red-200 px-4 py-2 font-bold text-red-700">Descartar</button><button disabled={saving} onClick={() => void continueAfterSave()} className="rounded-full bg-brand-orange px-4 py-2 font-bold text-white">Guardar y continuar</button></div></div></div> : null}</WorkspaceShell>;
}
function Public({ config, url, update }: { config: Config; url: string; update: (key: keyof Settings, value: string | boolean | number | null) => void }) {
  const theme = config.settings.publicTheme || "classic";
  const accent = config.settings.accentColor || "#FF5A00";
  const chooseTheme = (next: (typeof publicThemes)[number]) => {
    update("publicTheme", next.key);
    if (accent.toUpperCase() === "#FF5A00" && next.accent !== "#FF5A00") update("accentColor", next.accent);
  };
  return <section className="rounded-[26px] border border-brand-line bg-white p-5">
    <div className="flex justify-between"><div><h2 className="font-extrabold">Habilitar reservas online</h2><p className="text-sm text-neutral-500">Los horarios se administran en Reservas.</p></div></div>
    <div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Link público"><input readOnly value={url} className="foodie-input" /></Field><div className="flex gap-2 self-end"><button onClick={() => navigator.clipboard.writeText(url)} className="rounded-full border p-3"><Copy className="h-4 w-4" /></button><a href={url} target="_blank" className="rounded-full bg-brand-orange p-3 text-white"><ExternalLink className="h-4 w-4" /></a></div><Field label="Mínimo de personas online"><input type="number" value={config.settings.minPartySize} onChange={e => update("minPartySize", Number(e.target.value))} className="foodie-input" /></Field><Field label="Máximo de personas online"><input type="number" value={config.settings.maxPartySize} onChange={e => update("maxPartySize", Number(e.target.value))} className="foodie-input" /></Field></div>
    <div className="mt-8 border-t border-brand-line pt-6">
      <h3 className="font-extrabold">Apariencia del portal</h3><p className="text-sm text-neutral-500">Elegí el estilo y el color que verán tus clientes al reservar.</p>
      <p className="mt-5 text-sm font-semibold text-brand-ink">Estilo</p>
      <div className="mt-3 grid gap-3 sm:grid-cols-3">{publicThemes.map(item => { const active = theme === item.key; return <button key={item.key} type="button" aria-pressed={active} onClick={() => chooseTheme(item)} className={`rounded-2xl border p-3 text-left transition ${active ? "border-brand-orange bg-[#FFF4ED] ring-2 ring-[#FF5A00]/20" : "border-brand-line bg-white hover:border-brand-orange/50"}`}><span className="flex gap-1.5">{item.swatch.map(color => <span key={color} className="h-5 w-5 rounded-full border border-black/10" style={{ backgroundColor: color }} />)}</span><span className="mt-2 block font-bold text-brand-ink">{item.label}</span><span className="mt-1 block text-xs text-neutral-500">{item.description}</span></button>; })}</div>
      <p className="mt-5 text-sm font-semibold text-brand-ink">Color de acento</p>
      <div className="mt-3 flex flex-wrap items-center gap-3">
        <label className="flex items-center gap-2 rounded-full border border-brand-line px-3 py-2"><input type="color" value={accent} onChange={e => update("accentColor", e.target.value.toUpperCase())} className="h-7 w-7 cursor-pointer rounded-full border-0 bg-transparent p-0" aria-label="Color de acento" /><span className="text-sm font-bold uppercase text-brand-ink">{accent}</span></label>
        {accentPresets.map(color => <button key={color} type="button" onClick={() => update("accentColor", color)} aria-label={`Usar color ${color}`} title={color} className={`h-8 w-8 rounded-full border-2 transition ${accent.toUpperCase() === color ? "border-brand-ink" : "border-black/10 hover:border-brand-ink/40"}`} style={{ backgroundColor: color }} />)}
      </div>
      <p className="mt-3 text-xs text-neutral-500">El estilo <b>Actual</b> mantiene el diseño que ya tenías. <b>Campo</b> y <b>Bistró</b> cambian tipografía, superficies y formas, y usan este color como acento.</p>
    </div>
  </section>;
}
function Rules({ settings, update }: { settings: Settings; update: (key: keyof Settings, value: string | boolean | number | null) => void }) { return <section className="rounded-[26px] border border-brand-line bg-white p-5"><h2 className="font-extrabold">Reglas generales</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Anticipación mínima (minutos)"><input type="number" value={settings.minAdvanceMinutes} onChange={e => update("minAdvanceMinutes", Number(e.target.value))} className="foodie-input" /></Field><Field label="Anticipación máxima (días)"><input type="number" value={settings.maxAdvanceDays} onChange={e => update("maxAdvanceDays", Number(e.target.value))} className="foodie-input" /></Field></div></section>; }
function Schedules({ branches, windows, update }: { branches: Config["restaurant"]["branches"]; windows: Window[]; update: (branchId: string, weekday: number, service: Window["service"], key: keyof Window, value: string | boolean | number) => void }) { return <section className="rounded-[26px] border border-brand-line bg-white p-5"><h2 className="font-extrabold">Horarios por sede</h2>{branches.map(branch => <div key={branch.id} className="mt-6">{days.map((day, weekday) => <div key={day} className="border-t py-3"><b>{day}</b>{services.map(service => { const row = windows.find(x => x.branchId === branch.id && x.weekday === weekday && x.service === service.key)!; return <div key={service.key} className="mt-2 grid grid-cols-4 gap-2"><label className="flex items-center gap-2"><input type="checkbox" checked={row.isEnabled} onChange={e => update(branch.id, weekday, service.key, "isEnabled", e.target.checked)} />{service.label}</label><input type="time" value={row.startTime} onChange={e => update(branch.id, weekday, service.key, "startTime", e.target.value)} className="foodie-input py-2" /><input type="time" value={row.endTime} onChange={e => update(branch.id, weekday, service.key, "endTime", e.target.value)} className="foodie-input py-2" /><input type="number" min="5" value={row.intervalMin} onChange={e => update(branch.id, weekday, service.key, "intervalMin", Number(e.target.value))} className="foodie-input py-2" /></div>; })}</div>)}</div>)}</section>; }
function Exceptions({ branches, values, add, update, remove }: { branches: Config["restaurant"]["branches"]; values: Exception[]; add: (branchId: string) => void; update: (index: number, patch: Partial<Exception>) => void; remove: (index: number) => void }) { return <section className="rounded-[26px] border border-brand-line bg-white p-5"><div className="flex justify-between gap-4"><div><h2 className="font-extrabold">Excepciones de calendario</h2><p className="text-sm text-neutral-500">Marcá los cierres o cambios de horario por fecha.</p></div>{branches.map(branch => <button key={branch.id} onClick={() => add(branch.id)} className="rounded-full border border-brand-orange px-4 py-2 font-bold text-brand-orange">Agregar fecha · {branch.name}</button>)}</div><div className="mt-5 space-y-3">{values.map((item, index) => <div key={`${item.branchId}-${index}`} className="grid gap-3 rounded-2xl border p-4 md:grid-cols-[1fr_1fr_1fr_auto]"><select value={item.branchId} onChange={e => update(index, { branchId: e.target.value })} className="foodie-input">{branches.map(branch => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select><input type="date" value={item.serviceDate} onChange={e => update(index, { serviceDate: e.target.value })} className="foodie-input" /><select value={item.type} onChange={e => update(index, { type: e.target.value, windows: e.target.value === "closed" ? [] : item.windows })} className="foodie-input"><option value="closed">Cerrado todo el día</option><option value="custom_hours">Horario especial</option></select><button onClick={() => remove(index)} className="rounded-full border border-red-200 px-4 py-2 font-bold text-red-600">Eliminar</button></div>)}</div></section>; }
